# Generated by Django 5.2.4 on 2025-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_age_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский'), ('ANOTHER', 'Другой')], default='MALE', max_length=10),
        ),
    ]
