# Generated by Django 5.2.4 on 2025-07-16 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_age_alter_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessagestorage',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserLikedStatusStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_search_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_initiator_user', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_target_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('initiator_user', 'target_user')},
            },
        ),
    ]
