# Generated by Django 5.2.4 on 2025-07-16 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usermessagestorage_target_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, to='core.interest'),
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('swiped_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL)),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swiper', 'swiped_on')},
            },
        ),
    ]
